### ISSUE TITLE
Write Hostname File?

### ISSUE THREAD

**Issue by PolynomialDivision** [Freifunk-Spalter/bbb-configs#23]
Do we maybe just want to write a statistic hostname file, since we have here all information we need?

**Comment by Akira25** [comment]
Wouldn't that effectively stop hostname-resolution for any hostname, that is not part of bbb-configs? In addition, we would need to maintain that list. That would introduce more workload, wouldn't it?

**Comment by spolack** [comment]
host-name resolution is implemented
