### ISSUE TITLE
add alias neigh.sh to the images

### ISSUE THREAD

**Issue by pmelange** [Freifunk-Spalter/bbb-configs#26]
Without the script, neigh.sh, it is not very easy to debug problems on a node.  The bbb-configs router do not have this automatically installed.  It would be highly useful to have this script.

**Comment by spolack** [comment]
I agree with @Akira25, this shall be rather packaged.

**Comment by PolynomialDivision** [comment]
> I agree with @Akira25, this shall be rather packaged.

Please feel free to add this as PR to openwrt/routing.

**Comment by Akira25** [comment]
`neigh.sh` is packages in `falter-common-olsr`.
https://github.com/Freifunk-Spalter/packages/tree/master/packages/falter-common/files-olsrv1/usr/bin

It should be enough to install that package in bbb-config-images too, shouldn't it?

**Comment by spolack** [comment]
Is fixed with #44

**Comment by Akira25** [comment]
please add the alias `neigh.sh` from falter-common too. Most users know this script at the old name and signalised, that they'd like to keep it that way.

**Comment by spolack** [comment]
That symlink should be provided from the upstream package isnt it?

**Comment by Akira25** [comment]
no it shouldn't. I think its berlin-specific. In addition I don't like to wait again 3 weeks for just copy-and-paste to be merged. This alias is defined in the package `falter-common` installing it on the images should just be fine.

**Comment by spolack** [comment]
As falter-common will contains that alias, i'd propose to pull that in.

You can orientate on the following change.

https://github.com/Freifunk-Spalter/bbb-configs/commit/b6930b3d9bc2695f001013f3e287cbe4ba1c334b

**Comment by spolack** [comment]
@Akira25 provided a PR #50 which has been merged.  From now on new images will contain that alias.
