### ISSUE TITLE
load-balancing OWM-updates

### ISSUE THREAD

**Issue by SvenRoederer** [Freifunk-Spalter/bbb-configs#32]
By following d115c261b8e13625b09deefdb7a7788a89669c3b I just saw the hardcoded time when OWM-updates are pushed in  https://github.com/Freifunk-Spalter/bbb-configs/blob/1346e70c88d1cf97ed3abf38e4787e3625ec8caa/roles/cfg_openwrt/files/corerouter/crontabs/root#L1

The initial intention was to have every node using a random time to update its data, so some kind of even distribution should be archived. Avoiding a load-peak as 100 nodes update at exact the same moment.

**Comment by Akira25** [comment]
@spolack @nick Is it really necessary to hardcode that stuff in the bbb-configs? The owm-package will handle the crontab-entry by itself upon installation. It will set a random minute of the hour as push-time then.

**Comment by spolack** [comment]
I didnt notice there was some randomization implement orginally. Thank you for the hint. Are we already hitting criticial limits?


I created that file, in order to quickly bring up airmax_dfs_reset, of which a proper packaging is outstanding.

Until this is done i'd keep that as it is, since openwrt doesnt provide a ability to put you cronjabs into different files. (cron.d)

**Comment by spolack** [comment]
If the load is rather critical, we could template that crontab and randomize at rendering time in the mean time.

**Comment by Akira25** [comment]
Maybe I didn't get the problem right, but couldn't you just install owm-script after you had installed airmax_dfs_reset? It adds itself to the crontab:
https://github.com/Freifunk-Spalter/packages/blob/master/luci/luci-app-falter-owm/files/owm-defaults

**Comment by spolack** [comment]
The issue is, that the files are being injected *after* the packages have been installed. If we simply remove that crontab entry, we would end up without that.

**Comment by SvenRoederer** [comment]
In https://github.com/openwrt/packages/pull/15667 & https://github.com/openwrt/packages/pull/13345 there is some discussion on "cron.d"-style crontab-file (as you know from most fat-unix systems). This feature can solve your loop, by just maintaining a "owm crontab" which can have a package-default, that can safely manipulated later by other scripts / tools too.
