### ISSUE TITLE
Add Device: Mikrotik SXTsq Lite2

### ISSUE THREAD

**Issue by Akira25** [Freifunk-Spalter/bbb-configs#41]
We plan to deploy a setup with a core router and 4 AP's of SXTsq Lite2. It would be great if we can use bbb-configs for that, but we would need to have that device included. Is that possible? @spolack

**Comment by spolack** [comment]
Sure its possible. I think i prepared something, but didnt push yet..

**Comment by spolack** [comment]
Is there anything left, which is missing to close that ticket?
