### ISSUE TITLE
Add hostname support for even more devices

### ISSUE THREAD

**Issue by pmelange** [Freifunk-Spalter/bbb-configs#49]
For example, at hds, there could be a hostname hds-switch
Or even better, at emma there could be hostnames hds-switch0 hds-switch1 hds-switch2...

**Comment by PolynomialDivision** [comment]
As I read the ansible script, this is announced? Just to the assignment in the network config?

**Comment by pmelange** [comment]
These are network devices, not mesh devices.  So no, it doesn't go in /etc/config/network.  Just in the olsrd nameservice config

**Comment by PolynomialDivision** [comment]
https://github.com/Freifunk-Spalter/bbb-configs/commit/8e13400e4fb35ffe073f40bf3b624bcc032a7d5a

It does not filter on mesh?

**Comment by pmelange** [comment]
I don't understand your question

**Comment by spolack** [comment]
No one hinders you on describing them in assignments. Nick pointed you to the template, where the vars are being rendered.

Not an issue tbh

**Comment by spolack** [comment]
Closing as this feature is implemented. It only needs to be used.
